version: '3.8'

services:
  minecraft-beyond-mines-exosphere:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    container_name: minecraft-beyond-mines-exosphere
    hostname: minecraft-beyond-mines-exosphere
    ports:
      - "25565:25565" # The parent needs to expose 25565
    volumes:
      - ./minecraft-data:/minecraft:rw
    environment:
      - EULA=TRUE
    restart: unless-stopped