version: '3.8'

services:
  minecraft-25w14craftmine:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    container_name: minecraft-25w14craftmine
    hostname: minecraft-25w14craftmine
    ports:
      - "25567:25565" # The parent needs to expose 25567
    volumes:
      - ./minecraft-data:/minecraft:rw
    environment:
      - EULA=TRUE
    restart: unless-stopped