version: '3.8'

services:
  minecraft-monifactory:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    container_name: minecraft-monifactory
    hostname: minecraft-monifactory
    ports:
      - "25568:25565" # The parent needs to expose 25568
      - "25575:25575" # RCON port 
    volumes:
      - ./minecraft-data:/minecraft:rw
    environment:
      - EULA=TRUE
    restart: unless-stopped